### ISSUE TITLE
Unable to initiate user with multi-user image

### ISSUE THREAD

**Issue by taophp** [fpiesche/docker-mailpile#10]
I tried to make mailpile-multiuser work on a Raspberry PI 3 with Raspbian.
Here is my `docker-compose.yml`:
```yaml
version: '3'

volumes:
  mailpile-steph:
  mailpile-christel:

services:
  mailpile:
    image: florianpiesche/mailpile-multiuser
    restart: unless-stopped
    volumes:
      - mailpile-steph:/home/pirate/Data/mailpile/steph
      - mailpile-christel:/home/pirate/Data/mailpile/christel
    ports:
      - 10081:80
    environment:
      MAILPILE_USERS: "steph christel"
```
 Users defined in the `MAILPILE_USERS` does not exists locally, but the `/home/pirate/Data/mailpile/steph` directory exists, with all right for everybody.

I tried to login as steph. So a script tried to initiate the user of mailpile. Below, the output:
```
This is a script to launch Mailpile as a specific user.
The user must already have Mailpile configured.

Usage: mailpile-launcher.py USERNAME IDLE-QUIT-SECONDS URL

 That user has never run Mailpile. Aborting. 

Location: /mailpile/steph/
Expires: 0

==> sudo /usr/share/mailpile/multipile/mailpile-launcher.py steph 900 127.0.0.1:54511/mailpile/steph/
==[ FAILED! Exit code: 768 ]==
```

Can you help me to solve this problem ?
