### ISSUE TITLE
GPG Key generation failed

### ISSUE THREAD

**Issue by MalteKiefer** [fpiesche/docker-mailpile#12]
Hi,

I use your docker-compose for mailpile:

```
version: '2'

volumes:
  mailpile:

services:
  mailpile:
    image: florianpiesche/mailpile:nightly
    restart: always
    volumes:
      - mailpile:/home/mailpile/.local/share/Mailpile
    ports:
      - 8888:33411

```

But every time I try to generate the GPG for an account, it failed. I get this in the logs:

```
Traceback (most recent call last):sage
mailpile-mailpile-1  |   File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 1724, in run
mailpile-mailpile-1  |     gpg.chat(self.gpg_args(), self.run_script, self.main_script)
mailpile-mailpile-1  |   File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 1482, in chat
mailpile-mailpile-1  |     return callback(proc, *args, **kwargs)
mailpile-mailpile-1  |   File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 1707, in run_script
mailpile-mailpile-1  |     self.expect_exact(proc, exp, timeout=tmo)
mailpile-mailpile-1  |   File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 1695, in expect_exact
mailpile-mailpile-1  |     if RunTimed(timeout, self._expecter, proc, exp, timebox):
mailpile-mailpile-1  |   File "/usr/lib/python2.7/dist-packages/mailpile/util.py", line 1150, in RunTimed
mailpile-mailpile-1  |     RunTimedThread(func.__name__, work, unique=unique).run_timed(timeout)
mailpile-mailpile-1  |   File "/usr/lib/python2.7/dist-packages/mailpile/util.py", line 1131, in run_timed
mailpile-mailpile-1  |     raise TimedOut('Timed out: %s' % self.name)
mailpile-mailpile-1  | TimedOut: Timed out: _expecter
```

It looks like this here: https://github.com/mailpile/Mailpile/issues/1489
I try every time, autocrypt v 1.1.

Can you help me?
